print("Numele, prenumele:Elena Romasenco")
print("Data nasterii: 03.06.2004")
print("Email: lenaromasenco@gmail.com")
print("Adresa: Konev 42")
print("Locul de studii: Liceul teoretic Mihai Eminescu")
print("Numarul de telefon: 079143702")